=== BoJaN77799/XML-Veb-Servisi/XML Sheme sa dokumentima/odgovori.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://www.vakc-sistem.rs/odgovori"
    xmlns="http://www.vakc-sistem.rs/odgovori">

    <xs:element name="Odgovori">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="Odgovor">
                    <xs:annotation>
                            <xs:appinfo>
                                <jxb:property name="Odgovori"/>
                            </xs:appinfo>
                        </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="Vakcina" type="xs:string">
	                                <xs:annotation>
			                            <xs:appinfo>
			                                <jxb:property name="Vakcine"/>
			                            </xs:appinfo>
			                        </xs:annotation>
			                    </xs:element>
                            </xs:sequence>
                            <xs:element minOccurs="0" name="Grad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Termin">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Vrednost" type="xs:nonNegativeInteger"/>
                            <xs:element minOccurs="0" name="Ustanova">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Dodeljena_vakcina">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Razlog">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Indikator" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="2"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BoJaN77799/XML-Veb-Servisi/XML Sheme sa dokumentima/odgovori.xml
<?xml version="1.0" encoding="UTF-8"?>
<Odgovori xmlns="http://www.vakc-sistem.rs/odgovori"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakc-sistem.rs/odgovori odgovori.xsd">
    <Odgovor Indikator="Da">
        <Vakcina>Pfizer</Vakcina>
        <Grad>Becej</Grad>
        <Termin>2022-02-15 11:00</Termin>        
        <Vrednost>4</Vrednost>
        <Ustanova>Glavna Bolnica Beceja</Ustanova>
        <Dodeljena_vakcina>Pfizer</Dodeljena_vakcina>
        <Razlog>Uspesno pronadjen Termin!</Razlog>
        <Email>marko@markovic.gmail</Email>
    </Odgovor>
    <Odgovor Indikator="Ne">
        <Vakcina>Pfizer</Vakcina>
        <Vakcina>Sputnik V</Vakcina>
        <Grad>Becej</Grad>
        <Termin>2022-02-15 11:00</Termin>
        <Vrednost>4</Vrednost>
        <Ustanova>Glavna Bolnica Beceja</Ustanova>
        <Dodeljena_vakcina>Pfizer</Dodeljena_vakcina>
        <Razlog>Uspesno pronadjen Termin!</Razlog>
        <Email>marko@markovic.gmail</Email>
    </Odgovor>
</Odgovori>
