=== BoJaN77799/XML-Veb-Servisi/Sheme za projekat sa dokumentima/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://www.vakc-sistem.rs/interesovanje"
    xmlns="http://www.vakc-sistem.rs/interesovanje">
    <xs:element name="Interesovanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Drzavljanstvo">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="Domace_drzavljanstvo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="JMBG">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern
                                                  value="(0[1-9]|[12]\d|3[01])(0[1-9]|1[0-2])\d{3}\d{2}\d{4}"
                                                  />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Strano_drzavljanstvo_bez_boravka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Br_pasosa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern
                                                  value="^[A-Z0-9&lt;]{9}[0-9]{1}[A-Z]{3}[0-9]{7}[A-Z]{1}[0-9]{7}[A-Z0-9&lt;]{14}[0-9]{2}$"
                                                  />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Strano_drzavljanstvo_sa_boravkom">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Evidencioni_broj_stranca">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Ime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                            <xs:maxLength value="20"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Prezime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                            <xs:maxLength value="20"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Kontakt">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Broj_telefona">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{7,12}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_fiksnosg_telefona">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{7,10}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Email_adresa">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Opstina_vakcinisanja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Vrsta_vakcine">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="1" name="Vakcina">
                                <xs:complexType>
                                    <xs:attribute name="Tip" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="1" name="Dobrovoljni_davalac">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Da"/>
                            <xs:enumeration value="Ne"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="Id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BoJaN77799/XML-Veb-Servisi/ImunizacijaApplication/ImunizacijaApp/data/xml_example/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<Interesovanje xmlns="http://www.vakc-sistem.rs/interesovanje" xmlns:util="http://www.vakc-sistem.rs/util" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vakc-sistem.rs/interesovanje interesovanje.xsd" Id="2312312">
    <Drzavljanstvo Tip="DOMACE">
        <util:JMBG>0101999404404</util:JMBG>
    </Drzavljanstvo>
    <Ime>Marko</Ime>
    <Prezime>Markovic</Prezime>
    <Kontakt>
        <Broj_telefona xmlns="http://www.vakc-sistem.rs/util">1245125125</Broj_telefona>
        <Broj_fiksnosg_telefona xmlns="http://www.vakc-sistem.rs/util">858584858</Broj_fiksnosg_telefona>
        <Email_adresa xmlns="http://www.vakc-sistem.rs/util">markomarkovic@gmail.rs</Email_adresa>
    </Kontakt>
    <Opstina_vakcinisanja>Becej</Opstina_vakcinisanja>
    <Vakcina Tip="Pfizer"/>
    <Dobrovoljni_davalac>Da</Dobrovoljni_davalac>
    <Datum>2022-01-07</Datum>
</Interesovanje>

=== BoJaN77799/XML-Veb-Servisi/Sheme za projekat sa dokumentima/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<Interesovanje xmlns="http://www.vakc-sistem.rs/interesovanje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakc-sistem.rs/interesovanje interesovanje.xsd"
    Id="123123">
    <Drzavljanstvo>
        <Domace_drzavljanstvo>
            <JMBG>0101999103012</JMBG>
        </Domace_drzavljanstvo>
    </Drzavljanstvo>
    <Ime>Marko</Ime>
    <Prezime>MarkoviÄ‡</Prezime>
    <Kontakt>
        <Broj_telefona>062123456</Broj_telefona>
        <Broj_fiksnosg_telefona>695421412</Broj_fiksnosg_telefona>
        <Email_adresa>markomarkovic@gmail.com</Email_adresa>
    </Kontakt>
    <Opstina_vakcinisanja>Novi Sad</Opstina_vakcinisanja>
    <Vrsta_vakcine>
        <Vakcina Tip="Pfizer"/>
        <Vakcina Tip="Sinopharm"/>
    </Vrsta_vakcine>
    <Dobrovoljni_davalac>Da</Dobrovoljni_davalac>
    <Datum>2021-12-05</Datum>
</Interesovanje>
