=== BoJaN77799/XML-Veb-Servisi/Sheme za projekat sa dokumentima/portvrda_o_vakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://www.vakc-sistem.rs/potvrda-o-vakcinaciji"
    xmlns="http://www.vakc-sistem.rs/potvrda-o-vakcinaciji">

    <xs:element name="Potvrda_o_vakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podaci_o_primaocu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Prezime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Musko"/>
                                        <xs:enumeration value="Zensko"/>
                                        <xs:enumeration value="Ostalo"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="JMBG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="(0[1-9]|[12]\d|3[01])(0[1-9]|1[0-2])\d{3}\d{2}\d{4}"
                                        />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_vakcini">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Naziv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Zdravstvena_ustanova">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Doze">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="1" name="Doza">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Datum" type="xs:date"/>
                                                  <xs:element name="Serija">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:maxLength value="8"/>
                                                  <xs:minLength value="6"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="Redni_broj" use="required">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="1"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element minOccurs="0" name="DatumNaredneDoze" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_potvrdi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Datum_izdavanja" type="xs:date"/>
                            <xs:element name="QRCode">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="Sifra_potvrde" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BoJaN77799/XML-Veb-Servisi/Sheme za projekat sa dokumentima/portvrda_o_vakcinaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda_o_vakcinaciji xmlns="http://www.vakc-sistem.rs/potvrda-o-vakcinaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakc-sistem.rs/potvrda-o-vakcinaciji portvrda_o_vakcinaciji.xsd" Sifra_potvrde="1525124">
    <Podaci_o_primaocu>
        <Ime>Marko</Ime>
        <Prezime>MarkoviÄ‡</Prezime>
        <Datum_rodjenja>1999-01-01</Datum_rodjenja>
        <Pol>Musko</Pol>
        <JMBG>0101999103012</JMBG>
    </Podaci_o_primaocu>
    <Podaci_o_vakcini>
        <Naziv>Pfizer</Naziv>
        <Zdravstvena_ustanova>Dom Zdravlja "Novi Sad"</Zdravstvena_ustanova>
        <Doze>
            <Doza Redni_broj="1">
                <Datum>2021-10-08</Datum>
                <Serija>512512</Serija>
            </Doza>
        </Doze>
        <DatumNaredneDoze>2021-10-29</DatumNaredneDoze>
    </Podaci_o_vakcini>
    <Podaci_o_potvrdi>
        <Datum_izdavanja>2021-12-08</Datum_izdavanja>
        <QRCode>http://www.vakc-sistem.rs/qr-codes/Qr2</QRCode>
    </Podaci_o_potvrdi>
</Potvrda_o_vakcinaciji>
