=== BoJaN77799/XML-Veb-Servisi/Sheme za projekat sa dokumentima/zahtev_za_izdavanje_zelenog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.vakc-sistem.rs/zahtev-dzs" vc:minVersion="1.1"
    xmlns="http://www.vakc-sistem.rs/zahtev-dzs"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">

    <xs:element name="Zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podnosilac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Prezime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Musko"/>
                                        <xs:enumeration value="Zensko"/>
                                        <xs:enumeration value="Ostalo"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="JMBG" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="(0[1-9]|[12]\d|3[01])(0[1-9]|1[0-2])\d{3}\d{2}\d{4}"
                                        />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_pasosa" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="6"/>
                                        <xs:maxLength value="20"/>
                                        <xs:pattern value="[0-9A-Z]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Razlog">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Mesto">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="Id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BoJaN77799/XML-Veb-Servisi/ImunizacijaApplication/ImunizacijaApp/data/xml_example/zahtev_za_izdavanje_zelenog.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev xmlns="http://www.vakc-sistem.rs/zahtev-dzs"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.vakc-sistem.rs/zahtev-dzs zahtev_za_izdavanje_zelenog.xsd" Id="123124">
    <Podnosilac>
        <Ime xmlns="http://www.vakc-sistem.rs/util">Pera</Ime>
        <Prezime xmlns="http://www.vakc-sistem.rs/util">Peric</Prezime>
        <Datum_rodjenja xmlns="http://www.vakc-sistem.rs/util">1999-01-01</Datum_rodjenja>
        <Pol xmlns="http://www.vakc-sistem.rs/util">Musko</Pol>
        <JMBG xmlns="http://www.vakc-sistem.rs/util">0101999404404</JMBG>
        <Broj_pasosa xmlns="http://www.vakc-sistem.rs/util">125125126</Broj_pasosa>
    </Podnosilac>
    <Razlog>Da imam</Razlog>
    <Mesto>Novi Sad</Mesto>
    <Datum>2022-01-01</Datum>
</Zahtev>

=== BoJaN77799/XML-Veb-Servisi/Sheme za projekat sa dokumentima/zahtev_za_izdavanje_zelenog.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev xmlns="http://www.vakc-sistem.rs/zahtev-dzs"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakc-sistem.rs/zahtev-dzs zahtev_za_izdavanje_zelenog.xsd" Id="145434423">
    <Podnosilac>
        <Ime>Marko</Ime>
        <Prezime>Marković</Prezime>
        <Datum_rodjenja>1999-01-01</Datum_rodjenja>
        <Pol>Musko</Pol>
        <JMBG>0101999103012</JMBG>
        <Broj_pasosa>G1245125</Broj_pasosa>
    </Podnosilac>
    <Razlog>Želim da idem na apsolventsku ekskurziju</Razlog>
    <Mesto>Bečej</Mesto>
    <Datum>2021-12-06</Datum>
</Zahtev>
